// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	models "github.com/RyseUp/in-game-item-system/internal/models"
)

// InventoryRecord is an autogenerated mock type for the InventoryRecord type
type InventoryRecord struct {
	mock.Mock
}

// CreateRecord provides a mock function with given fields: ctx, tx, record
func (_m *InventoryRecord) CreateRecord(ctx context.Context, tx *gorm.DB, record *models.InventoryRecord) error {
	ret := _m.Called(ctx, tx, record)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.InventoryRecord) error); ok {
		r0 = rf(ctx, tx, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInventoryRecord creates a new instance of InventoryRecord. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryRecord(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryRecord {
	mock := &InventoryRecord{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
