// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	models "github.com/RyseUp/in-game-item-system/internal/models"
)

// Inventory is an autogenerated mock type for the Inventory type
type Inventory struct {
	mock.Mock
}

// BeginTransaction provides a mock function with no fields
func (_m *Inventory) BeginTransaction() *gorm.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// CreateInventory provides a mock function with given fields: ctx, tx, inventory
func (_m *Inventory) CreateInventory(ctx context.Context, tx *gorm.DB, inventory *models.Inventory) error {
	ret := _m.Called(ctx, tx, inventory)

	if len(ret) == 0 {
		panic("no return value specified for CreateInventory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.Inventory) error); ok {
		r0 = rf(ctx, tx, inventory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetInventoryByUserIDAndItemID provides a mock function with given fields: ctx, userID, itemID
func (_m *Inventory) GetInventoryByUserIDAndItemID(ctx context.Context, userID string, itemID string) (*models.Inventory, error) {
	ret := _m.Called(ctx, userID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for GetInventoryByUserIDAndItemID")
	}

	var r0 *models.Inventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Inventory, error)); ok {
		return rf(ctx, userID, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Inventory); ok {
		r0 = rf(ctx, userID, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Inventory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateInventoryQuantity provides a mock function with given fields: ctx, tx, inventory
func (_m *Inventory) UpdateInventoryQuantity(ctx context.Context, tx *gorm.DB, inventory *models.Inventory) error {
	ret := _m.Called(ctx, tx, inventory)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInventoryQuantity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.Inventory) error); ok {
		r0 = rf(ctx, tx, inventory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInventory creates a new instance of Inventory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventory(t interface {
	mock.TestingT
	Cleanup(func())
}) *Inventory {
	mock := &Inventory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
