// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/inventory/v1/inventory.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryAPI_UserGetInventory_FullMethodName       = "/api.inventory.v1.InventoryAPI/UserGetInventory"
	InventoryAPI_UserAddItemInInventory_FullMethodName = "/api.inventory.v1.InventoryAPI/UserAddItemInInventory"
	InventoryAPI_UserUseItemInInventory_FullMethodName = "/api.inventory.v1.InventoryAPI/UserUseItemInInventory"
)

// InventoryAPIClient is the client API for InventoryAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryAPIClient interface {
	UserGetInventory(ctx context.Context, in *UserGetInventoryRequest, opts ...grpc.CallOption) (*UserGetInventoryResponse, error)
	UserAddItemInInventory(ctx context.Context, in *UserAddItemInInventoryRequest, opts ...grpc.CallOption) (*UserAddItemInInventoryResponse, error)
	UserUseItemInInventory(ctx context.Context, in *UserUseItemInInventoryRequest, opts ...grpc.CallOption) (*UserUseItemInInventoryResponse, error)
}

type inventoryAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryAPIClient(cc grpc.ClientConnInterface) InventoryAPIClient {
	return &inventoryAPIClient{cc}
}

func (c *inventoryAPIClient) UserGetInventory(ctx context.Context, in *UserGetInventoryRequest, opts ...grpc.CallOption) (*UserGetInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGetInventoryResponse)
	err := c.cc.Invoke(ctx, InventoryAPI_UserGetInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryAPIClient) UserAddItemInInventory(ctx context.Context, in *UserAddItemInInventoryRequest, opts ...grpc.CallOption) (*UserAddItemInInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAddItemInInventoryResponse)
	err := c.cc.Invoke(ctx, InventoryAPI_UserAddItemInInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryAPIClient) UserUseItemInInventory(ctx context.Context, in *UserUseItemInInventoryRequest, opts ...grpc.CallOption) (*UserUseItemInInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserUseItemInInventoryResponse)
	err := c.cc.Invoke(ctx, InventoryAPI_UserUseItemInInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryAPIServer is the server API for InventoryAPI service.
// All implementations must embed UnimplementedInventoryAPIServer
// for forward compatibility.
type InventoryAPIServer interface {
	UserGetInventory(context.Context, *UserGetInventoryRequest) (*UserGetInventoryResponse, error)
	UserAddItemInInventory(context.Context, *UserAddItemInInventoryRequest) (*UserAddItemInInventoryResponse, error)
	UserUseItemInInventory(context.Context, *UserUseItemInInventoryRequest) (*UserUseItemInInventoryResponse, error)
	mustEmbedUnimplementedInventoryAPIServer()
}

// UnimplementedInventoryAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryAPIServer struct{}

func (UnimplementedInventoryAPIServer) UserGetInventory(context.Context, *UserGetInventoryRequest) (*UserGetInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGetInventory not implemented")
}
func (UnimplementedInventoryAPIServer) UserAddItemInInventory(context.Context, *UserAddItemInInventoryRequest) (*UserAddItemInInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserAddItemInInventory not implemented")
}
func (UnimplementedInventoryAPIServer) UserUseItemInInventory(context.Context, *UserUseItemInInventoryRequest) (*UserUseItemInInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserUseItemInInventory not implemented")
}
func (UnimplementedInventoryAPIServer) mustEmbedUnimplementedInventoryAPIServer() {}
func (UnimplementedInventoryAPIServer) testEmbeddedByValue()                      {}

// UnsafeInventoryAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryAPIServer will
// result in compilation errors.
type UnsafeInventoryAPIServer interface {
	mustEmbedUnimplementedInventoryAPIServer()
}

func RegisterInventoryAPIServer(s grpc.ServiceRegistrar, srv InventoryAPIServer) {
	// If the following call pancis, it indicates UnimplementedInventoryAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryAPI_ServiceDesc, srv)
}

func _InventoryAPI_UserGetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryAPIServer).UserGetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryAPI_UserGetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryAPIServer).UserGetInventory(ctx, req.(*UserGetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryAPI_UserAddItemInInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAddItemInInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryAPIServer).UserAddItemInInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryAPI_UserAddItemInInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryAPIServer).UserAddItemInInventory(ctx, req.(*UserAddItemInInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryAPI_UserUseItemInInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUseItemInInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryAPIServer).UserUseItemInInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryAPI_UserUseItemInInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryAPIServer).UserUseItemInInventory(ctx, req.(*UserUseItemInInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryAPI_ServiceDesc is the grpc.ServiceDesc for InventoryAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.inventory.v1.InventoryAPI",
	HandlerType: (*InventoryAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserGetInventory",
			Handler:    _InventoryAPI_UserGetInventory_Handler,
		},
		{
			MethodName: "UserAddItemInInventory",
			Handler:    _InventoryAPI_UserAddItemInInventory_Handler,
		},
		{
			MethodName: "UserUseItemInInventory",
			Handler:    _InventoryAPI_UserUseItemInInventory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/inventory/v1/inventory.proto",
}
